name: Send a HTTP Request when new RSS item is detected - SimRacing Unlimited
on:
  rss:
    url: https://simracing-unlimited.com/de/feed
    config:
      active: false
      loglevel: debug
      
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request - RSS SimRacing Unlimited
        uses: actionsflow/axios@main
        with:
          url: ${{secrets.WEBHOOK_RIBTECH_EXTERNNEWS}}
          method: POST
          body: |
            {
              "username": "SimRacing Unlimited",
              "avatar_url": "https://pbs.twimg.com/profile_images/1316315799691431937/78yP9Jiu_400x400.jpg",
              "content": "**<<<${{on.rss.outputs.title}}>>>**\n<<<${{on.rss.outputs.link}}>>>"
              
            }
            
