name: Send a HTTP Request when new RSS item is detected
on:
  rss:
    url: https://news.google.com/rss?hl=de&gl=DE&ceid=DE:de
    config:
      customFields:
        item: source
      loglevel: debug
      
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request      
        uses: actionsflow/axios@main
        with:
          url: ${{secrets.WEBHOOK_TEST}}
          method: POST
          body: |
            {
              "username": "Top-Meldungen - Google News",
              "content": "**<<<${{on.rss.outputs.title}}>>>**\n<<<${{on.rss.outputs.link}}>>>\n<<<${{on.rss.outputs}}>>>"
              
            }

#"avatar_url": "https://pbs.twimg.com/profile_images/1316315799691431937/78yP9Jiu_400x400.jpg",
