env:
  RSS_NAME: Test RSS
name: Send a HTTP Request when new RSS item is detected - ${{ env.RSS_NAME }}
on:
  rss:
    url: https://news.google.com/rss?hl=de&gl=DE&ceid=DE:de
    parserConfig:
      customFields:
        item:
          - source
    config:
      loglevel: debug
      
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request - RSS ${{ env.RSS_NAME }}
        uses: actionsflow/axios@main
        with:
          url: ${{secrets.WEBHOOK_TEST}}
          method: POST
          body: |
            {
              "username": "${{on.rss.outputs.source}}",
              "content": "**<<<${{on.rss.outputs.title}}>>>**\n<<<${{on.rss.outputs.link}}>>>"
              
            }
    config:
      loglevel: debug
#"avatar_url": "https://pbs.twimg.com/profile_images/1316315799691431937/78yP9Jiu_400x400.jpg",
