name: Send a HTTP Request when new RSS item is detected
on:
  rss:
    url: https://news.google.com/rss?hl=de&gl=DE&ceid=DE:de
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Make a HTTP Request      
        uses: actionsflow/axios@main
        with:
          url: https://discord.com/api/webhooks/1068519234927329280/lnTl7vGuqvpekjXzoo89sdIq6mgf9J-XKj8L11LGFlnAX8YEThHE06z4jYUEbxFkguis
          method: POST
          body: |
            {
              "username": "Google News",
              "avatar_url": "https://pbs.twimg.com/profile_images/1316315799691431937/78yP9Jiu_400x400.jpg",
              "content": "**<<<${{on.rss.outputs.title}}>>>**\n<<<${{on.rss.outputs.link}}>>>"
            }
